-- Create the 'profiles' table to store user profile data.
-- This table will have a single row for the portfolio, identified by id = 1.
CREATE TABLE
  public.profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "profilePictureUrl" TEXT NULL,
    name TEXT NULL,
    bio TEXT NULL,
    "socialLinks" JSONB NULL,
    "customLinks" JSONB NULL,
    CONSTRAINT profiles_pkey PRIMARY KEY (id)
  );

-- Enable Row Level Security (RLS) for the 'profiles' table.
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows public read access to the profiles data.
-- This is necessary for the public-facing profile page to fetch the data.
CREATE POLICY "Enable read access for all users" ON public.profiles FOR
SELECT
  USING (true);

-- Create a storage bucket named 'linkfolio-images' for storing profile and link images.
-- Make this bucket public so that images can be easily accessed.
INSERT INTO
  storage.buckets (id, name, public)
VALUES
  ('linkfolio-images', 'linkfolio-images', TRUE) ON CONFLICT (id) DO NOTHING;

-- Create a policy that allows anyone to view images in the 'linkfolio-images' bucket.
-- This is required for the images to be displayed on your public profile.
CREATE POLICY "Public Read Access" ON storage.objects FOR
SELECT
  USING (bucket_id = 'linkfolio-images');

-- Create a policy that allows authenticated users to upload images to the bucket.
-- In our setup, this means anyone who is logged into the admin dashboard.
-- Note: Supabase's default 'anon' key is treated as an authenticated role for this policy.
CREATE POLICY "Allow authenticated uploads" ON storage.objects FOR INSERT
WITH
  CHECK (bucket_id = 'linkfolio-images' AND auth.role () = 'anon');